version: "3"

services:
  nginx:
    networks: 
      - diabetes-detection-network
    image: nginx:latest
    container_name: type2-nginx
    restart: unless-stopped
    tty: true
    ports: 
      - "8001:80"
      - "443:443"
    volumes: 
      - ./app/web/src:/var/www/html
      - ./app/web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 
      - mysql

  tf-serving:
    image: tensorflow/serving
    tty: true
    container_name: type2-tf-serving
    ports:
      - "8501:8501"
      - "8500:8500"
    environment:
      MODEL_NAME: best_nn_model
    volumes:
      - ./app/models/best_nn_model/1:/models/best_nn_model/1

  app:
    build:
      context: ./app/web
      dockerfile: Dockerfile
      args:
        user: wes
        uid: 1000
    tty: true
    container_name: type2-app
    ports: 
      - "9000:9000"
      - "3000:3000"
    working_dir: /var/www/html
    volumes: 
      - ./app/web/src:/var/www/html
      - ./app/web/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment: 
      SERVICE_NAME: app
      SERVICE_TAGS: php
    depends_on:
      - mysql
    networks:
      - diabetes-detection-network

  mysql:
    image: mysql:latest
    container_name: type2-mysql
    ports: 
      - "3307:3306"
    restart: "unless-stopped"
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: didetection
      MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: mysql-dev
      SERVICE_NAME: mysql
    volumes:
      - ./app/web/mysql-data:/var/lib/mysql
    networks: 
      - diabetes-detection-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: type2-phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on: 
      - mysql
    ports:
      - 8080:80
    networks:
      - diabetes-detection-network

#Volumes - Volume accessible across all services
volumes: 
  mysql-data:
    driver: local

networks:
  diabetes-detection-network:
    driver: bridge
